---
title: "Parte de excel"
author: "Kevin David Calderon Martinez"
format: pdf
fontsize: 12pt
mainfont: "Arial"
geometry: "margin = 2.54cm"
colorlinks: true
urlcolor: blue
linestretch: 1.5
include-in-header:
  text: |
      \usepackage{indentfirst}
      \usepackage{hanging}
      \usepackage{caption}
      \usepackage{titling}
       
      \setlength{\parindent}{1.27cm}
      \setlength{\parskip}{0pt}
      \captionsetup[table]{name=Tabla}
      \captionsetup[table]{font=small}
      \captionsetup[figure]{name=Figura}
      \captionsetup[figure]{font=small}
      
      \addtokomafont{section}{\rmfamily}
      \addtokomafont{subsection}{\rmfamily}
      \addtokomafont{subsubsection}{\rmfamily}
      
      \RedeclareSectionCommand[
        beforeskip=1pt,
        afterskip=1pt
      ]{section}

      \RedeclareSectionCommand[
        beforeskip=4pt,
        afterskip=4pt
      ]{subsection}

      \RedeclareSectionCommand[
        beforeskip=3pt,
        afterskip=3pt
      ]{subsubsection}
      
      \pretitle{\begin{center}\fontsize{18pt}{20pt}\selectfont\bfseries}
      \posttitle{\par\end{center}}
      
      \preauthor{\begin{center}\fontsize{12pt}{14pt}\selectfont}
      \postauthor{\par\end{center}}
      \predate{\begin{center}\fontsize{12pt}{14pt}\selectfont}
      \postdate{\par\end{center}}      
---

Primero, leemos la base de datos.

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(here)

datos <- read.table(here("data", "moras.txt"), header = TRUE, sep = ",", dec = ".", stringsAsFactors = FALSE )

```


## Ejercicio 2


```{r, echo = FALSE, warning = FALSE, message = FALSE}

datos$SALARIO <- gsub("\"", "", datos$SALARIO)      
datos$SALARIO <- gsub(",", ".", datos$SALARIO) 
datos$SALARIO <- as.numeric(datos$SALARIO) 

resumen <- data.frame(
  MEDIDOR = c("MINIMO", "MAXIMO", "CUARTIL_1", "MEDIANA", "CUARTIL_3", "PROMEDIO"),
  SALARIO = c(
    min(datos$SALARIO, na.rm = TRUE),
    max(datos$SALARIO, na.rm = TRUE),
    quantile(datos$SALARIO, 0.25, na.rm = TRUE),
    median(datos$SALARIO, na.rm = TRUE),
    quantile(datos$SALARIO, 0.75, na.rm = TRUE),
    mean(datos$SALARIO, na.rm = TRUE)
  ),
  EDAD = c(
    min(datos$EDAD, na.rm = TRUE),
    max(datos$EDAD, na.rm = TRUE),
    quantile(datos$EDAD, 0.25, na.rm = TRUE),
    median(datos$EDAD, na.rm = TRUE),
    quantile(datos$EDAD, 0.75, na.rm = TRUE),
    mean(datos$EDAD, na.rm = TRUE)
  )
)
knitr::kable(resumen, caption = "Resumen de 5 numeros y promedio.")
```

## Ejercicio 3

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)

datos <- datos %>%
  mutate(
    Z_SALARIO = (SALARIO - mean(SALARIO, na.rm = TRUE)) / sd(SALARIO, na.rm = TRUE),
    OUTLIER_SALARIO = ifelse(abs(Z_SALARIO) > 1.96, "OUTLIER", "NO"),

    Z_EDAD = (EDAD - mean(EDAD, na.rm = TRUE)) / sd(EDAD, na.rm = TRUE),
    OUTLIER_EDAD = ifelse(abs(Z_EDAD) > 1.96, "OUTLIER", "NO")
  )
zscore <- datos %>% 
  select(Z_SALARIO, OUTLIER_SALARIO, Z_EDAD, OUTLIER_EDAD) %>% 
  head(10)
knitr::kable(zscore, caption = "Aplicacion del Z-score.")
```

## Ejercicio 4

```{r, echo = FALSE, warning = FALSE, message = FALSE}
porcentaje_na <- sapply(datos, function(x) {
  sum(is.na(x)) / length(x) * 100
})
na <- data.frame(
  COLUMNA = names(porcentaje_na),
  PORCENTAJE = round(porcentaje_na, 2)
)
knitr::kable(na, caption = "Porcentaje de valores nulos en cada columna.")
```

## Ejercicio 5

```{r, echo = FALSE, warning = FALSE, message = FALSE}

datos <- datos %>%
  mutate(
    SALARIO_IMPUT = ifelse(
      is.na(SALARIO) | SALARIO == "",
      mean(as.numeric(SALARIO), na.rm = TRUE),
      SALARIO
    ),
    
    EDAD_IMPUT = ifelse(
      is.na(EDAD) | EDAD == "",
      round(mean(as.numeric(EDAD), na.rm = TRUE)),
      EDAD
    ),
    
    TIPO_ASEGURAMIENTO_IMPUT = ifelse(
      is.na(TIPO_ASEGURAMIENTO) | TIPO_ASEGURAMIENTO == "",
      "DESCONOCIDO",
      TIPO_ASEGURAMIENTO
    )
  )

imputs <- datos %>% 
  select (SALARIO_IMPUT, EDAD_IMPUT, TIPO_ASEGURAMIENTO_IMPUT) %>% 
  head(10)

knitr::kable(imputs, caption = "Datos imputados por las columnas vacias.")

```

